# Generated by Django 5.0.6 on 2024-06-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='code',
            new_name='customer_code',
        ),
    ]
