# Generated by Django 5.0.6 on 2024-06-26 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_rename_code_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
